//! Axis geometry matches CairoMakie: viewports, final limits (incl. `aspect` and
//! `autolimitaspect`) and the boxes of tick labels, axis labels and titles, for the reference
//! figures of `examples/fidelity_check.rs`. The Makie side is `tests/fixtures/fidelity_makie.json`
//! (generated by `tools/fidelity_check.jl`).

#[path = "../examples/fidelity_check.rs"]
mod fidelity_check;

#[test]
fn axis_geometry_matches_cairomakie() {
    let json = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/fidelity_makie.json"))
        .expect("tests/fixtures/fidelity_makie.json");
    let makie: serde_json::Value = serde_json::from_str(&json).unwrap();
    // Makie computes in Float32: agreement to ~1e-4 units is exact.
    let worst = fidelity_check::check(&makie, false);
    assert!(worst < 1e-3, "largest difference vs CairoMakie: {worst} units");
}
