//! Tick machinery vs. Makie 0.24 / PlotUtils 1.5 reference values (`tests/fixtures/ticks.json`,
//! generated by `tools/gen_tick_fixtures.jl`). Every comparison is exact: bitwise `f64` equality
//! and identical label strings.

use ezviz::__ticks as t;
use ezviz::{MinorSpec, RichText, Scale, TickFormat, TickSpec, Wilkinson, format_ticks_auto};
use serde_json::Value;

fn fixtures() -> Value {
    let s = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/ticks.json")).unwrap();
    serde_json::from_str(&s).unwrap()
}

fn num(v: &Value) -> f64 {
    match v.as_str().unwrap() {
        "Inf" => f64::INFINITY,
        "-Inf" => f64::NEG_INFINITY,
        "NaN" => f64::NAN,
        s => s.parse().unwrap(),
    }
}

fn nums(v: &Value) -> Vec<f64> {
    v.as_array().unwrap().iter().map(num).collect()
}

fn same(a: &[f64], b: &[f64]) -> bool {
    a.len() == b.len() && a.iter().zip(b).all(|(x, y)| x.to_bits() == y.to_bits() || (x.is_nan() && y.is_nan()))
}

type Spans = Vec<(String, String)>;

fn fixture_labels(v: &Value) -> Vec<Spans> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|l| {
            l.as_array()
                .unwrap()
                .iter()
                .map(|s| (s[0].as_str().unwrap().to_string(), s[1].as_str().unwrap().to_string()))
                .collect()
        })
        .collect()
}

fn our_labels(ls: &[RichText]) -> Vec<Spans> {
    ls.iter()
        .map(|l| {
            l.spans
                .iter()
                .map(|s| {
                    let kind = if s.baseline_shift > 0.0 {
                        "sup"
                    } else if s.baseline_shift < 0.0 {
                        "sub"
                    } else {
                        "plain"
                    };
                    (s.text.clone(), kind.to_string())
                })
                .collect()
        })
        .collect()
}

fn scale(s: &str) -> Scale {
    match s {
        "log10" => Scale::Log10,
        "log2" => Scale::Log2,
        "log" => Scale::Ln,
        _ => Scale::Identity,
    }
}

/// Runs `check` on every case of a section; prints mismatches and the pass rate, returns failures.
fn section(name: &str, cases: &Value, check: impl Fn(&Value) -> Result<(), String>) -> usize {
    let cases = cases.as_array().unwrap();
    let mut fails = 0;
    for c in cases {
        if let Err(e) = check(c) {
            fails += 1;
            if fails <= 15 {
                eprintln!("[{name}] {e}");
            }
        }
    }
    eprintln!("{name}: {}/{} exact", cases.len() - fails, cases.len());
    fails
}

#[test]
fn makie_fixtures() {
    let fx = fixtures();
    let mut fails = 0;

    fails += section("wilkinson", &fx["wilkinson"], |c| {
        let (lo, hi) = (num(&c["lo"]), num(&c["hi"]));
        let k = |n: &str| c[n].as_u64().unwrap() as usize;
        let w = Wilkinson { k_ideal: k("k_ideal"), k_min: k("k_min"), k_max: k("k_max"), ..Wilkinson::new(5) };
        let got = w.tick_values(lo, hi);
        let want = nums(&c["values"]);
        if !same(&got, &want) {
            return Err(format!("({lo:?}, {hi:?}) {w:?}: got {got:?}, want {want:?}"));
        }
        if c.get("labels").is_some() {
            let got = our_labels(&format_ticks_auto(&got));
            let want = fixture_labels(&c["labels"]);
            if got != want {
                return Err(format!("labels ({lo:?}, {hi:?}): got {got:?}, want {want:?}"));
            }
        }
        Ok(())
    });

    fails += section("format", &fx["format"], |c| {
        let xs = nums(&c["values"]);
        let got = our_labels(&format_ticks_auto(&xs));
        let want = fixture_labels(&c["labels"]);
        if got != want { Err(format!("{xs:?}: got {got:?}, want {want:?}")) } else { Ok(()) }
    });

    fails += section("log", &fx["log"], |c| {
        let (lo, hi) = (num(&c["lo"]), num(&c["hi"]));
        let s = c["scale"].as_str().unwrap();
        let (vals, labels) = t::log_makie(lo, hi, scale(s)).unwrap();
        let want = nums(&c["values"]);
        if !same(&vals, &want) {
            return Err(format!("{s} ({lo:?}, {hi:?}): got {vals:?}, want {want:?}"));
        }
        let (got, want) = (our_labels(&labels), fixture_labels(&c["labels"]));
        if got != want { Err(format!("{s} labels ({lo:?}, {hi:?}): got {got:?}, want {want:?}")) } else { Ok(()) }
    });

    fails += section("minor", &fx["minor"], |c| {
        let (lo, hi) = (num(&c["lo"]), num(&c["hi"]));
        let n = c["n"].as_u64().unwrap() as usize;
        let s = c["scale"].as_str().unwrap();
        let ticks = nums(&c["ticks"]);
        let got = t::intervals_between(n, scale(s), &ticks, lo, hi);
        let want = nums(&c["values"]);
        if !same(&got, &want) {
            Err(format!("n={n} {s} ({lo:?}, {hi:?}) ticks {ticks:?}: got {got:?}, want {want:?}"))
        } else {
            Ok(())
        }
    });

    fails += section("ranges", &fx["ranges"], |c| {
        let want = nums(&c["values"]);
        let got = match c["kind"].as_str().unwrap() {
            "colon" => t::colon(num(&c["a"]), num(&c["s"]), num(&c["b"])),
            _ => t::linspace(num(&c["a"]), num(&c["b"]), c["n"].as_i64().unwrap()),
        }
        .unwrap_or_default();
        if !same(&got, &want) { Err(format!("{c}: got {got:?}")) } else { Ok(()) }
    });

    fails += section("math", &fx["math"], |c| {
        let f = c["f"].as_str().unwrap();
        let got =
            if f == "pow10" { t::powi10(c["x"].as_str().unwrap().parse().unwrap()) } else { t::math(f, num(&c["x"])) };
        let want = num(&c["y"]);
        if !same(&[got], &[want]) { Err(format!("{f}({}): got {got:?}, want {want:?}", c["x"])) } else { Ok(()) }
    });

    fails += section("shortest", &fx["shortest"], |c| {
        let x = num(&c["x"]);
        let (got, want) = (t::shortest_e10(x), c["e10"].as_i64().unwrap());
        if got != want { Err(format!("{x:?}: got {got}, want {want}")) } else { Ok(()) }
    });

    fails += section("sigdigits", &fx["sigdigits"], |c| {
        let (x, n) = (num(&c["x"]), c["n"].as_i64().unwrap());
        let (got, want) = (t::round_sigdigits(x, n), num(&c["y"]));
        if !same(&[got], &[want]) {
            Err(format!("round({x:?}; sigdigits={n}): got {got:?}, want {want:?}"))
        } else {
            Ok(())
        }
    });

    assert_eq!(fails, 0, "{fails} fixture mismatches (see stderr)");
}

fn texts(ls: &[RichText]) -> Vec<String> {
    ls.iter().map(|l| l.plain_text()).collect()
}

#[test]
fn automatic_linear_ticks() {
    let (v, l) = TickSpec::Automatic.compute(&TickFormat::Automatic, 0.55, 10.45, Scale::Identity);
    assert_eq!(v, [2.0, 4.0, 6.0, 8.0, 10.0]);
    assert_eq!(texts(&l), ["2", "4", "6", "8", "10"]);
    // Either order.
    let (v2, _) = TickSpec::Automatic.compute(&TickFormat::Automatic, 10.45, 0.55, Scale::Identity);
    assert_eq!(v, v2);
    // Non-finite limits give no ticks instead of panicking.
    let (v, _) = TickSpec::Automatic.compute(&TickFormat::Automatic, f64::NAN, 1.0, Scale::Identity);
    assert!(v.is_empty());
}

#[test]
fn log_integer_default() {
    let (v, l) = TickSpec::Automatic.compute(&TickFormat::Automatic, 0.8, 1200.0, Scale::Log10);
    assert_eq!(v, [1.0, 10.0, 100.0, 1000.0]);
    assert_eq!(l[0].spans[0].text, "10");
    assert_eq!(l[0].spans[1].text, "0");
    assert!(l[0].spans[1].baseline_shift > 0.0);
    let (_, l) = TickSpec::Automatic.compute(&TickFormat::Automatic, 1e-3, 0.5, Scale::Log10);
    assert_eq!(l[0].spans[1].text, "\u{2212}3");

    // Many decades: whole-decade steps.
    let (v, _) = TickSpec::Automatic.compute(&TickFormat::Automatic, 1e-12, 1e12, Scale::Log10);
    let e: Vec<i32> = v.iter().map(|x| x.log10().round() as i32).collect();
    assert!(e.len() >= 3 && e.windows(2).all(|w| w[1] - w[0] == e[1] - e[0]), "{e:?}");
    assert!(v.iter().all(|x| format!("{x:e}").starts_with("1e")), "{v:?}");

    // Less than two decades: linear ticks with plain labels.
    let (v, l) = TickSpec::Automatic.compute(&TickFormat::Automatic, 2.0, 30.0, Scale::Log10);
    assert_eq!(v, [10.0, 20.0, 30.0]);
    assert_eq!(texts(&l), ["10", "20", "30"]);

    // Makie-exact LogTicks can land between decades.
    let (v, l) = TickSpec::LogMakie.compute(&TickFormat::Automatic, 1.0, 10.0, Scale::Log10);
    assert_eq!(v.len(), 3);
    assert_eq!(texts(&l), ["100.0", "100.5", "101.0"]);
}

#[test]
fn log_minors() {
    let major = [1.0, 10.0, 100.0];
    let m = MinorSpec::Auto.compute(&major, 0.8, 120.0, Scale::Log10);
    let want: Vec<f64> =
        [0.8, 0.9, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0]
            .into_iter()
            .collect();
    assert_eq!(m, want);
    // Majors skipping decades: minors at the skipped decades.
    let m = MinorSpec::Auto.compute(&[1e-4, 1.0, 1e4], 1e-5, 1e5, Scale::Log10);
    assert_eq!(m, [1e-5, 1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3, 1e5]);
    // Makie's IntervalsBetween(9) on consecutive decades gives the same 2..9 minors.
    let m = MinorSpec::IntervalsBetween(9).compute(&major, 1.0, 100.0, Scale::Log10);
    assert_eq!(m, [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0]);
}

#[test]
fn linear_minors() {
    let m = MinorSpec::Auto.compute(&[2.0, 4.0, 6.0, 8.0, 10.0], 0.55, 10.45, Scale::Identity);
    assert_eq!(m, [1.0, 3.0, 5.0, 7.0, 9.0]);
    let m = MinorSpec::IntervalsBetween(5).compute(&[0.0, 1.0], -0.3, 1.3, Scale::Identity);
    assert_eq!(m.len(), 4 + 1 + 1);
    let m = MinorSpec::Values(vec![0.5, 5.0]).compute(&[], 0.0, 1.0, Scale::Identity);
    assert_eq!(m, [0.5]);
}

#[test]
fn specs_and_formats() {
    use ezviz::Conv;
    let s: TickSpec = [0.0, 1.0, 2.0].conv();
    let (v, l) = s.compute(&TickFormat::Automatic, -0.5, 1.5, Scale::Identity);
    assert_eq!(v, [0.0, 1.0]);
    assert_eq!(texts(&l), ["0", "1"]);

    let s: TickSpec = (0..=10).step_by(5).conv();
    let (v, _) = s.compute(&TickFormat::Automatic, 0.0, 10.0, Scale::Identity);
    assert_eq!(v, [0.0, 5.0, 10.0]);

    let s: TickSpec = (vec![1.0, 2.0], vec!["a", "b"]).conv();
    let (_, l) = s.compute(&TickFormat::Automatic, 0.0, 3.0, Scale::Identity);
    assert_eq!(texts(&l), ["a", "b"]);

    let f: TickFormat = (|v: f64| format!("{v:.1}")).conv();
    let (_, l) = TickSpec::Automatic.compute(&f, 0.0, 10.0, Scale::Identity);
    assert_eq!(texts(&l), ["0.0", "5.0", "10.0"]);

    let f: TickFormat = "{:.2f} s".conv();
    let (_, l) = TickSpec::Values(vec![1.5]).compute(&f, 0.0, 3.0, Scale::Identity);
    assert_eq!(texts(&l), ["1.50 s"]);

    let s: TickSpec = (|lo: f64, hi: f64| vec![lo, (lo + hi) / 2.0, hi]).conv();
    let (v, _) = s.compute(&TickFormat::Automatic, 0.0, 4.0, Scale::Identity);
    assert_eq!(v, [0.0, 2.0, 4.0]);

    // A custom formatter on a log axis replaces the 10ⁿ labels (Makie).
    let f: TickFormat = (|v: f64| format!("{v}")).conv();
    let (_, l) = TickSpec::Automatic.compute(&f, 1.0, 100.0, Scale::Log10);
    assert_eq!(texts(&l), ["1", "10", "100"]);
}

#[test]
#[should_panic(expected = "tick labels")]
fn labeled_length_mismatch() {
    use ezviz::Conv;
    let _: TickSpec = (vec![1.0, 2.0], vec!["a"]).conv();
}
