# Generates src/color/cmap_data.rs: 256-entry colormap tables sampled the way Makie does.
#
#   julia --project=tools tools/gen_colormaps.jl
#
# Makie turns a colormap name into `to_colormap(name)` (the ColorSchemes.jl colors, e.g. 256 for
# viridis, 9 for Blues) and maps values with `interpolated_getindex` (linear interpolation in
# sRGB-encoded space; GLMakie's LUT texture does the same). Sampling that piecewise-linear gradient
# at 256 evenly spaced points gives a uniform LUT the GPU can interpolate again.

using Makie

const MAPS = [
    ("VIRIDIS", :viridis), ("MAGMA", :magma), ("INFERNO", :inferno), ("PLASMA", :plasma),
    ("CIVIDIS", :cividis), ("TURBO", :turbo), ("GRAYS", :grays), ("BLUES", :Blues),
    ("REDS", :Reds), ("BALANCE", :balance), ("RDBU", :RdBu), ("COOLWARM", :coolwarm),
]
const N = 256

f(x) = string(Float32(x))

out = IOBuffer()
println(out, "// Generated by tools/gen_colormaps.jl from Makie $(pkgversion(Makie)) (to_colormap +")
println(out, "// interpolated_getindex sampled at $N points). Do not edit.")
println(out, "#![allow(clippy::approx_constant)]")
println(out)
println(out, "/// `(Makie name, sRGB table)` for every built-in colormap, in `Colormap` id order.")
println(out, "pub(crate) static TABLES: [(&str, &[[f32; 3]; $N]); $(length(MAPS))] = [")
for (c, s) in MAPS
    println(out, "    (\"$(s)\", &$c),")
end
println(out, "];")
for (c, s) in MAPS
    cm = Makie.to_colormap(s)
    @assert all(x -> Makie.alpha(x) == 1, cm)
    println(out)
    println(out, "#[rustfmt::skip]")
    println(out, "static $c: [[f32; 3]; $N] = [")
    for i in 0:N-1
        col = Makie.interpolated_getindex(cm, i / (N - 1))
        println(out, "    [$(f(col.r)), $(f(col.g)), $(f(col.b))],")
    end
    println(out, "];")
end
path = joinpath(@__DIR__, "..", "src", "color", "cmap_data.rs")
write(path, take!(out))
println("wrote ", normpath(path))
