# Generates src/color/cmap_data.rs: 256-entry colormap tables sampled the way Makie does.
#
#   julia --project=tools tools/gen_colormaps.jl
#
# Makie turns a colormap name into `to_colormap(name)` (the ColorSchemes.jl colors, e.g. 256 for
# viridis, 9 for Blues) and maps values with `interpolated_getindex` (linear interpolation in
# sRGB-encoded space; GLMakie's LUT texture does the same). Sampling that piecewise-linear gradient
# at 256 evenly spaced points gives a uniform LUT the GPU can interpolate again.

using Makie

const MAPS = [
    ("VIRIDIS", :viridis), ("MAGMA", :magma), ("INFERNO", :inferno), ("PLASMA", :plasma),
    ("CIVIDIS", :cividis), ("TURBO", :turbo), ("GRAYS", :grays), ("BLUES", :Blues),
    ("REDS", :Reds), ("BALANCE", :balance), ("RDBU", :RdBu), ("COOLWARM", :coolwarm),
]
const N = 256

f(x) = string(Float32(x))

# The provenance header of the generated file (keep in sync with THIRD_PARTY_NOTICES.md).
const PROVENANCE = raw"""
//! Built-in colormap tables: 256 sRGB entries per map, in `Colormap` id order.
//!
//! Provenance: data from ColorSchemes 3.31.0 (MIT), reached through PlotUtils 1.5.0
//! `get_colorscheme` and Makie 0.24.14 `to_colormap`, sampled with Makie's `interpolated_getindex`
//! (exact for the 256-color maps, linearly resampled for the others). Per map, the upstream file
//! and the attribution or license it states (see THIRD_PARTY_NOTICES.md):
//! - viridis, magma, inferno, plasma: ColorSchemes `data/matplotlib.jl` (file header and
//!   `data/matplotliblicense.txt`: by Nathaniel J. Smith, Stefan van der Walt and, for viridis,
//!   Eric Firing; CC0).
//! - cividis: ColorSchemes `data/allcolorschemes.jl` (`:cividis`, noted "Cividis color scale for
//!   R"; no license stated).
//! - turbo: ColorSchemes `data/allcolorschemes.jl` (`:turbo`, noted "turbo, improved rainbow
//!   colormap, anton mikhailov"; `LICENSE.md`: Copyright 2019 Google LLC, Apache-2.0).
//! - grays: PlotUtils 1.5.0 `src/colorschemes.jl` (`MISC_COLORSCHEMES[:grays]`, gray 0.05 to 0.95;
//!   MIT).
//! - Blues, Reds, RdBu: ColorSchemes `data/colorbrewerschemes.jl` (`:Blues_9`, `:Reds_9`,
//!   `:RdBu_11` via PlotUtils' `COLORSCHEME_ALIASES`; `data/colorbrewerlicense.txt`: Copyright (c)
//!   2002 Cynthia Brewer, Mark Harrower, and The Pennsylvania State University, Apache-2.0).
//! - balance: ColorSchemes `data/cmocean.jl` (cmocean; `data/cmoceanlicense.txt`: MIT, Copyright
//!   (c) 2015 Kristen M. Thyng).
//! - coolwarm: ColorSchemes `data/gnu.jl` (`:coolwarm`, 100 colors, noted "diverging bipolar color
//!   map was generated by Kenneth Moreland"; no license stated).
"""

out = IOBuffer()
println(out, "// Generated by tools/gen_colormaps.jl from Makie $(pkgversion(Makie)) (to_colormap +")
println(out, "// interpolated_getindex sampled at $N points). Do not edit.")
println(out)
print(out, PROVENANCE)
println(out, "#![allow(clippy::approx_constant)]")
println(out)
println(out, "/// `(Makie name, sRGB table)` for every built-in colormap, in `Colormap` id order.")
println(out, "pub(crate) static TABLES: [(&str, &[[f32; 3]; $N]); $(length(MAPS))] = [")
for (c, s) in MAPS
    println(out, "    (\"$(s)\", &$c),")
end
println(out, "];")
for (c, s) in MAPS
    cm = Makie.to_colormap(s)
    @assert all(x -> Makie.alpha(x) == 1, cm)
    println(out)
    println(out, "#[rustfmt::skip]")
    println(out, "static $c: [[f32; 3]; $N] = [")
    for i in 0:N-1
        col = Makie.interpolated_getindex(cm, i / (N - 1))
        println(out, "    [$(f(col.r)), $(f(col.g)), $(f(col.b))],")
    end
    println(out, "];")
end
path = joinpath(@__DIR__, "..", "src", "color", "cmap_data.rs")
write(path, take!(out))
println("wrote ", normpath(path))
